server:
  port: 9042

logging:
  level:
    root: INFO

spring:
  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 200MB
  http:
    multipart:
      enabled=false:
  application:
    name: naga-server
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.83.120:3306/naga_dev?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: "!Qaz123456"

custom:
  hadoop:
    rm:
      uri: node03.kaikeba.com:8088
    nn:
      uri: node01.kaikeba.com:50070
    conf: hadop的site和core两个配置文件目录
    proxyuser: root
    hivemetastore: thrift://192.168.83.100:9083
  task:
    packageDir: /home/jixin/imoocprojects/naga/packages  存储上传azkaban的zip包
    azkaban:
      server: http://192.168.83.120:8081
      user: azkaban
      password: azkaban
      execHome: /soft/home/azkaban-exec-server
    api:
      server: localhost
      port: "9042"
  presto:
    uri: jdbc:presto://192.168.83.120:9090/hive
  hive:
    uri: jdbc:hive2://192.168.83.120:10000/default
  spark:
    home: /soft/home/spark-2.4.4-bin-hadoop2.7
  redis:
    ip: 192.168.83.120
    port: 6379
  ranger:
    url: http://47.108.140.82:6080
    user: admin
    pwd: admin
    service:
      hdfs: imooc_hdfs
      hive: imooc_hive